/* 
	the format of the tree definition file is simple,
	you can find specification in the Tigra Menu documentation at:
	
	http://www.softcomplex.com/products/tigra_menu/docs/items.html	
*/

var TREE_ITEMS = [
['OSS',null,
	['IRP', null,
		['IRP', null,
			 ['Renewals', '/forms90/f90servlet?config=IRP&form=oss_for_all.fmx',],
			 ['Estimator', '/prod/OSS_IRP_ESTIMATOR_OBJ_INTRA.OSS_IRP_WEB_ESTI_OPTION?username=<%=username%>',],
			 ['JD. CheckList', '/forms90/f90servlet?config=IRP&form=irp_data_check.fmx',],
			 ['Comp. Insurance', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
			 ['Fleet Insurance', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
			 ['Wts. Range/JD.', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
		],
		['Fee Schedules', null,
				['US','http://www.softcomplex.com/products.html#client_side',],
	    		['Canadian', null,
					['Quebec', 'http://www.softcomplex.com/products/tigra_menu/builder/'],
					['NB', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=33'],
					['NF', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=33'],
					['NS', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=33'],
					['NT', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=33'],
					['PE', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=33'],
					['YT', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=33'],
	    		],
		],
		['Plates', 'http://www.softcomplex.com/products.html#dotnet_components',
				['Plate Maint.','http://www.softcomplex.com/products.html#client_side',],
			    ['Plate Menu','http://www.softcomplex.com/products.html#client_side',],
			
		],
		['Permits', 'http://www.softcomplex.com/products.html#dotnet_components',],
		['Reports', 'http://www.softcomplex.com/products.html#client_side',
			 ['Renewals', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
			 ['Plate Inventory', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
			 ['Active Vehicles', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
			 ['Fleet Details', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
			 ['Stag. Distri.', 'http://www.softcomplex.com/products/tigra_menu_pro/',],
		]
	],
	['BAS',null,
	    ['Forms', null,
	        ['BAS','http://www.softcomplex.com/products.html#client_side',],
	        ['Insurance', 'http://www.softcomplex.com/products.html#client_side'],
	    ],
	    ['Reports', null,
       	    ['Renewal','http://www.softcomplex.com/products.html#client_side',],
	        ['Transmittals', 'http://www.softcomplex.com/products.html#client_side'],
			['Status', 'http://www.softcomplex.com/products.html#client_side'],
			['InsuranceCancel', 'http://www.softcomplex.com/products.html#client_side'],
			['BlankStatus', 'http://www.softcomplex.com/products.html#client_side'],
		],
	],
	['MAS', null,
	    ['Forms', null,
	        ['Payments','http://www.softcomplex.com/products.html#client_side',],
	        ['Inquiry', 'http://www.softcomplex.com/products.html#client_side'],
			['Disbursement', 'http://www.softcomplex.com/products.html#client_side'],
			['Trans.Address', 'http://www.softcomplex.com/products.html#client_side'],
			['WheelTax', 'http://www.softcomplex.com/products.html#client_side'],
			['ManualRefund', 'http://www.softcomplex.com/products.html#client_side'],
			['PlateRefund', 'http://www.softcomplex.com/products.html#client_side'],
			['DelPayment', 'http://www.softcomplex.com/products.html#client_side'],
			['OnlPayment', 'http://www.softcomplex.com/products.html#client_side'],
	    ],
	    ['Reports', null,
          	['EOD','http://www.softcomplex.com/products.html#client_side',],
	        ['User', 'http://www.softcomplex.com/products.html#client_side'],
			['Location', 'http://www.softcomplex.com/products.html#client_side'],
			['Mail&Online', 'http://www.softcomplex.com/products.html#client_side'],
			['DailyRcpt.', 'http://www.softcomplex.com/products.html#client_side'],
			['DailyDep', 'http://www.softcomplex.com/products.html#client_side'],
			['MonthlyDep', 'http://www.softcomplex.com/products.html#client_side'],
			['DelPaymentLog', 'http://www.softcomplex.com/products.html#client_side'],
		],
	],
	['PUC', null,
	    ['Forms', null,
	        ['PUC','http://www.softcomplex.com/products.html#client_side',],
	        ['Vehicles', 'http://www.softcomplex.com/products.html#client_side'],
	    ],
	    ['Reports', null,
          	['Certi.Veh','http://www.softcomplex.com/products.html#client_side',],
	        ['Claims/Qtr', 'http://www.softcomplex.com/products.html#client_side'],
			['Discrip.Ltr', 'http://www.softcomplex.com/products.html#client_side'],
		],
	],
	['OURS', 'http://dorbis02.dor.state.in.us/forms90/f90servlet?config=remedy&form=OSS_REMEDY.fmx'],
	['OS/OW', 'http://www.softcomplex.com/contacts.html'],
	['MISC.', null,
	   	    ['CabCards','/forms90/f90servlet?config=misc&form=IRP_cab_cards.fmx',],
	        ['Cred.& Labels', '/forms90/f90servlet?config=misc&form=USER_CREDENTIALS.fmx'],
			['Cashiers Cred.', '/forms90/f90servlet?config=misc&form=oss_mas_reports.fmx'],
	],
	],
	];


